//JSON JS OBJECT NOTATION
//aka valid js
//if you have it as json, json sees it as plain text
//plain text to obj that you can work with in js
//you need to call json.parse()
//afterwards, you would be able to treat it as an obj, and work with it as
//an obj
//'module.exports =" can then be used with require in server.js
//when server.js gets it, its already an obj for you
module.exports = {
  animals: [
    {
      id: 63594689,
      organization_id: "GA247",
      url: "https://www.petfinder.com/cat/15900-63594689/ga/covington/newton-county-animal-control-ga247/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Long Hair",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "15900",
      description: "Primary Color: Grey Secondary Color: White",
      organization_animal_id: "15900",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:28+0000",
      published_at: "2023-04-28T16:01:27+0000",
      distance: null,
      contact: {
        email: "newtonac@co.newton.ga.us",
        phone: "(770) 786-9514",
        address: {
          address1: "210 Lower River Rd.",
          address2: null,
          city: "Covington",
          state: "GA",
          postcode: "30016",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594689",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/ga247",
        },
      },
    },
    {
      id: 63594688,
      organization_id: "KY56",
      url: "https://www.petfinder.com/dog/annie-63594688/ky/glasgow/barren-river-animal-welfare-association-ky56/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Rottweiler",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Bicolor",
        secondary: "Black",
        tertiary: null,
      },
      age: "Young",
      gender: "Female",
      size: "Large",
      coat: "Short",
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Annie",
      description:
        "Annie was turned in as a stray on 4/14. She is about 7-8 months old and weighed 44.8 pounds. Her...",
      organization_animal_id: "52441926",
      photos: [
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680",
        },
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/2/?bust=1682697681&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/2/?bust=1682697681&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/2/?bust=1682697681&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/2/?bust=1682697681",
        },
      ],
      primary_photo_cropped: {
        small:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=300",
        medium:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=450",
        large:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680&width=600",
        full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594688/1/?bust=1682697680",
      },
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:23+0000",
      published_at: "2023-04-28T16:01:22+0000",
      distance: null,
      contact: {
        email: "syobymevol@scrtc.com",
        phone: "(270) 651-7297",
        address: {
          address1: "175 Trojan Trail",
          address2: null,
          city: "Glasgow",
          state: "KY",
          postcode: "42141",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594688",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ky56",
        },
      },
    },
    {
      id: 63594684,
      organization_id: "KS47",
      url: "https://www.petfinder.com/dog/heidi-63594684/ks/topeka/helping-hands-humane-society-ks47/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Chihuahua",
        secondary: "Terrier",
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Young",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: false,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Heidi",
      description:
        "Primary Color: Black W/white Weight: 10lbs Age: 0yrs 7mths 1wks Animal has been Spayed",
      organization_animal_id: "123303",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:20+0000",
      published_at: "2023-04-28T16:01:19+0000",
      distance: null,
      contact: {
        email: "adopt@hhhstopeka.org",
        phone: "785-233-7325",
        address: {
          address1: "5720 SW 21st St.",
          address2: null,
          city: "Topeka",
          state: "KS",
          postcode: "66604",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594684",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ks47",
        },
      },
    },
    {
      id: 63594685,
      organization_id: "KS47",
      url: "https://www.petfinder.com/dog/domino-63594685/ks/topeka/helping-hands-humane-society-ks47/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Pit Bull Terrier",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Domino",
      description:
        "Primary Color: Black W/white Weight: 48lbs Age: 2yrs 0mths 1wks Animal has been Neutered",
      organization_animal_id: "123226",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:20+0000",
      published_at: "2023-04-28T16:01:19+0000",
      distance: null,
      contact: {
        email: "adopt@hhhstopeka.org",
        phone: "785-233-7325",
        address: {
          address1: "5720 SW 21st St.",
          address2: null,
          city: "Topeka",
          state: "KS",
          postcode: "66604",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594685",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ks47",
        },
      },
    },
    {
      id: 63594686,
      organization_id: "KS47",
      url: "https://www.petfinder.com/dog/duke-63594686/ks/topeka/helping-hands-humane-society-ks47/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Labrador Retriever",
        secondary: "Pit Bull Terrier",
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Baby",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Duke",
      description:
        "Primary Color: White Weight: 17.5lbs Age: 0yrs 3mths 1wks Animal has been Neutered",
      organization_animal_id: "123283",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:20+0000",
      published_at: "2023-04-28T16:01:19+0000",
      distance: null,
      contact: {
        email: "adopt@hhhstopeka.org",
        phone: "785-233-7325",
        address: {
          address1: "5720 SW 21st St.",
          address2: null,
          city: "Topeka",
          state: "KS",
          postcode: "66604",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594686",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ks47",
        },
      },
    },
    {
      id: 63594687,
      organization_id: "KS47",
      url: "https://www.petfinder.com/dog/taurus-63594687/ks/topeka/helping-hands-humane-society-ks47/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Pit Bull Terrier",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Taurus",
      description:
        "Primary Color: Blue W/ White Weight: 38lbs Age: 6yrs 0mths 0wks Animal has been Neutered",
      organization_animal_id: "123229",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:20+0000",
      published_at: "2023-04-28T16:01:19+0000",
      distance: null,
      contact: {
        email: "adopt@hhhstopeka.org",
        phone: "785-233-7325",
        address: {
          address1: "5720 SW 21st St.",
          address2: null,
          city: "Topeka",
          state: "KS",
          postcode: "66604",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594687",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ks47",
        },
      },
    },
    {
      id: 63594682,
      organization_id: "TX570",
      url: "https://www.petfinder.com/dog/jada-63594682/tx/fort-davis/grand-companions-humane-society-tx570/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Doberman Pinscher",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Baby",
      gender: "Female",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Jada",
      description:
        "Primary Color: Black Secondary Color: Tan Weight: 12.2lbs Age: 0yrs 4mths 0wks Animal has been Spayed I am available for...",
      organization_animal_id: "11577",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:07+0000",
      published_at: "2023-04-28T16:01:06+0000",
      distance: null,
      contact: {
        email: "programs@grandcompanions.org",
        phone: "(432) 426-3724",
        address: {
          address1: "P.O. Box 1156",
          address2: "701 E. Compromise St.",
          city: "Fort Davis",
          state: "TX",
          postcode: "79734",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594682",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/tx570",
        },
      },
    },
    {
      id: 63594681,
      organization_id: "CA611",
      url: "https://www.petfinder.com/dog/blue-63594681/ca/napa/napa-county-animal-shelter-ca611/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Australian Cattle Dog / Blue Heeler",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: null,
        secondary: null,
        tertiary: null,
      },
      age: "Baby",
      gender: "Male",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Blue",
      description: "Primary Color: Blue Roan Weight: 9lbs Age: 0yrs 0mths 8wks",
      organization_animal_id: "42633",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:01:06+0000",
      published_at: "2023-04-28T16:01:05+0000",
      distance: null,
      contact: {
        email: "animal.shelter@countyofnapa.org",
        phone: "(707) 253-4382",
        address: {
          address1: "942 Hartle Ct.",
          address2: null,
          city: "Napa",
          state: "CA",
          postcode: "94559",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594681",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ca611",
        },
      },
    },
    {
      id: 63594678,
      organization_id: "VA117",
      url: "https://www.petfinder.com/dog/bonny-63594678/va/falls-church/lost-dog-and-cat-rescue-foundation-va117/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Australian Cattle Dog / Blue Heeler",
        secondary: "Labrador Retriever",
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Black",
        secondary: "Brown / Chocolate",
        tertiary: null,
      },
      age: "Baby",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Bonny",
      description:
        "Bonny will be attending one of our adoption events coming up this weekend! To learn more about our upcoming events...",
      organization_animal_id: "LDAC-A-35864",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:34+0000",
      published_at: "2023-04-28T16:00:33+0000",
      distance: null,
      contact: {
        email: "dogs@lostdogrescue.org",
        phone: "(703) 295-3647",
        address: {
          address1: "6801 Wilson Blvd.",
          address2: null,
          city: "Falls Church",
          state: "VA",
          postcode: "22044",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594678",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/va117",
        },
      },
    },
    {
      id: 63594677,
      organization_id: "AR370",
      url: "https://www.petfinder.com/dog/lady-63594677/ar/little-rock/last-chance-arkansas-ar370/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Terrier",
        secondary: "Mixed Breed",
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Yellow / Tan / Blond / Fawn",
        secondary: "Gray / Blue / Silver",
        tertiary: null,
      },
      age: "Adult",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Lady",
      description: null,
      organization_animal_id: "LCA-A-1533",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:32+0000",
      published_at: "2023-04-28T16:00:31+0000",
      distance: null,
      contact: {
        email: "adoptions@lastchancear.org",
        phone: null,
        address: {
          address1: null,
          address2: null,
          city: "Little Rock",
          state: "AR",
          postcode: "72223",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594677",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/ar370",
        },
      },
    },
    {
      id: 63594674,
      organization_id: "AL43",
      url: "https://www.petfinder.com/cat/frasier-63594674/al/huntsville/greater-huntsville-humane-society-al43/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Short Hair",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Orange / Red",
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Extra Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Frasier",
      description:
        "Hi my name is Frasier! I am a big loveable boy who loves chin rubs. The GHHS staff are still...",
      organization_animal_id: "GHHS-A-4215",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:29+0000",
      published_at: "2023-04-28T16:00:28+0000",
      distance: null,
      contact: {
        email: "info@ghhs.org",
        phone: "(256) 881-8081",
        address: {
          address1: "2812 Johnson Road",
          address2: null,
          city: "Huntsville",
          state: "AL",
          postcode: "35805",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594674",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/al43",
        },
      },
    },
    {
      id: 63594675,
      organization_id: "FL77",
      url: "https://www.petfinder.com/cat/parsley-24001-63594675/fl/middleburg/safe-animal-shelter-fl77/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Short Hair",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Black",
        secondary: null,
        tertiary: null,
      },
      age: "Baby",
      gender: "Male",
      size: "Small",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Parsley 24001",
      description: null,
      organization_animal_id: "SAFE-A-22527",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:29+0000",
      published_at: "2023-04-28T16:00:28+0000",
      distance: null,
      contact: {
        email: "adoptions@safeanimalshelter.com",
        phone: "(904) 375-9122",
        address: {
          address1: "2913 County Road 220",
          address2: null,
          city: "Middleburg",
          state: "FL",
          postcode: "32068",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594675",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/fl77",
        },
      },
    },
    {
      id: 63594676,
      organization_id: "FL77",
      url: "https://www.petfinder.com/cat/sage-24002-63594676/fl/middleburg/safe-animal-shelter-fl77/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Short Hair",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Gray / Blue / Silver",
        secondary: null,
        tertiary: null,
      },
      age: "Baby",
      gender: "Male",
      size: "Small",
      coat: null,
      attributes: {
        spayed_neutered: false,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Sage 24002",
      description: null,
      organization_animal_id: "SAFE-A-22528",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:29+0000",
      published_at: "2023-04-28T16:00:28+0000",
      distance: null,
      contact: {
        email: "adoptions@safeanimalshelter.com",
        phone: "(904) 375-9122",
        address: {
          address1: "2913 County Road 220",
          address2: null,
          city: "Middleburg",
          state: "FL",
          postcode: "32068",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594676",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/fl77",
        },
      },
    },
    {
      id: 63594671,
      organization_id: "CA541",
      url: "https://www.petfinder.com/cat/harrison-63594671/ca/clovis/miss-winkles-pet-adoption-center-clovis-ca541/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Short Hair",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Tabby (Brown / Chocolate)",
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Medium",
      coat: "Short",
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Harrison",
      description:
        "Pictured: Harrison - M - 2 yrs. - Brown Tabby w/ White\n*Shy, FIV Positive\n\n*ADOPT\nTo adopt, simply come...",
      organization_animal_id: null,
      photos: [
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626",
        },
      ],
      primary_photo_cropped: {
        small:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=300",
        medium:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=450",
        large:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626&width=600",
        full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594671/1/?bust=1682697626",
      },
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:29+0000",
      published_at: "2023-04-28T16:00:28+0000",
      distance: null,
      contact: {
        email: "petadoptioncenter@cityofclovis.com",
        phone: "(559) 324-2465",
        address: {
          address1: null,
          address2: null,
          city: "Clovis",
          state: "CA",
          postcode: "93611",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594671",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/ca541",
        },
      },
    },
    {
      id: 63594673,
      organization_id: "PA1084",
      url: "https://www.petfinder.com/cat/pina-colada-63594673/pa/philadelphia/purr-philadelphia-urgent-rescue-and-relief-pa1084/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Cat",
      species: "Cat",
      breeds: {
        primary: "Domestic Short Hair",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Buff / Tan / Fawn",
        secondary: "White",
        tertiary: null,
      },
      age: "Baby",
      gender: "Male",
      size: "Small",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: false,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Pina Colada",
      description: null,
      organization_animal_id: "PRR-A-812",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:28+0000",
      published_at: "2023-04-28T16:00:27+0000",
      distance: null,
      contact: {
        email: "contact@purrphilly.com",
        phone: "(267) 939-9184",
        address: {
          address1: null,
          address2: null,
          city: "Philadelphia",
          state: "PA",
          postcode: "19146",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594673",
        },
        type: {
          href: "/v2/types/cat",
        },
        organization: {
          href: "/v2/organizations/pa1084",
        },
      },
    },
    {
      id: 63594667,
      organization_id: "AL01",
      url: "https://www.petfinder.com/dog/baby-63594667/al/montgomery/montgomery-humane-society-al01/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd Dog",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Black",
        secondary: "Yellow / Tan / Blond / Fawn",
        tertiary: null,
      },
      age: "Young",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Baby",
      description: null,
      organization_animal_id: "MGM-A-7031",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:23+0000",
      published_at: "2023-04-28T16:00:22+0000",
      distance: null,
      contact: {
        email: "msspeedy307@hotmail.com",
        phone: "(334) 409-0622 ",
        address: {
          address1: "1150 John Overton Drive",
          address2: null,
          city: "Montgomery",
          state: "AL",
          postcode: "36110",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594667",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/al01",
        },
      },
    },
    {
      id: 63594668,
      organization_id: "AL01",
      url: "https://www.petfinder.com/dog/angel-63594668/al/montgomery/montgomery-humane-society-al01/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "Terrier",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "White / Cream",
        secondary: "Yellow / Tan / Blond / Fawn",
        tertiary: null,
      },
      age: "Young",
      gender: "Female",
      size: "Medium",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Angel",
      description: null,
      organization_animal_id: "MGM-A-7182",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:23+0000",
      published_at: "2023-04-28T16:00:22+0000",
      distance: null,
      contact: {
        email: "msspeedy307@hotmail.com",
        phone: "(334) 409-0622 ",
        address: {
          address1: "1150 John Overton Drive",
          address2: null,
          city: "Montgomery",
          state: "AL",
          postcode: "36110",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594668",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/al01",
        },
      },
    },
    {
      id: 63594669,
      organization_id: "AL01",
      url: "https://www.petfinder.com/dog/achilles-63594669/al/montgomery/montgomery-humane-society-al01/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd Dog",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Yellow / Tan / Blond / Fawn",
        secondary: "Black",
        tertiary: null,
      },
      age: "Young",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: [],
      name: "Achilles",
      description: null,
      organization_animal_id: "MGM-A-7511",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:23+0000",
      published_at: "2023-04-28T16:00:22+0000",
      distance: null,
      contact: {
        email: "msspeedy307@hotmail.com",
        phone: "(334) 409-0622 ",
        address: {
          address1: "1150 John Overton Drive",
          address2: null,
          city: "Montgomery",
          state: "AL",
          postcode: "36110",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594669",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/al01",
        },
      },
    },
    {
      id: 63594670,
      organization_id: "AL01",
      url: "https://www.petfinder.com/dog/alexander-63594670/al/montgomery/montgomery-humane-society-al01/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd Dog",
        secondary: null,
        mixed: false,
        unknown: false,
      },
      colors: {
        primary: "Black",
        secondary: "Apricot / Beige",
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Large",
      coat: null,
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: ["Heartworm positive"],
      name: "Alexander",
      description: null,
      organization_animal_id: "MGM-A-7484",
      photos: [],
      primary_photo_cropped: null,
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T16:00:23+0000",
      published_at: "2023-04-28T16:00:22+0000",
      distance: null,
      contact: {
        email: "msspeedy307@hotmail.com",
        phone: "(334) 409-0622 ",
        address: {
          address1: "1150 John Overton Drive",
          address2: null,
          city: "Montgomery",
          state: "AL",
          postcode: "36110",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594670",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/al01",
        },
      },
    },
    {
      id: 63594665,
      organization_id: "PA275",
      url: "https://www.petfinder.com/dog/rio-63594665/pa/seneca/venango-county-humane-society-pa275/?referrer_id=6a117eae-ce60-4349-965d-d179cb856d01",
      type: "Dog",
      species: "Dog",
      breeds: {
        primary: "German Shepherd Dog",
        secondary: null,
        mixed: true,
        unknown: false,
      },
      colors: {
        primary: "Tricolor (Brown, Black, & White)",
        secondary: null,
        tertiary: null,
      },
      age: "Adult",
      gender: "Male",
      size: "Large",
      coat: "Medium",
      attributes: {
        spayed_neutered: true,
        house_trained: false,
        declawed: null,
        special_needs: false,
        shots_current: true,
      },
      environment: {
        children: null,
        dogs: null,
        cats: null,
      },
      tags: ["Friendly", "Quiet", "Loyal", "Gentle", "Smart"],
      name: "Rio",
      description:
        "Rio came to us as a stray so we have no history for him. The vet estimated his age to...",
      organization_animal_id: null,
      photos: [
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590",
        },
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/2/?bust=1682697590&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/2/?bust=1682697590&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/2/?bust=1682697590&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/2/?bust=1682697590",
        },
        {
          small:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/3/?bust=1682697591&width=100",
          medium:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/3/?bust=1682697591&width=300",
          large:
            "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/3/?bust=1682697591&width=600",
          full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/3/?bust=1682697591",
        },
      ],
      primary_photo_cropped: {
        small:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=300",
        medium:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=450",
        large:
          "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590&width=600",
        full: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/63594665/1/?bust=1682697590",
      },
      videos: [],
      status: "adoptable",
      status_changed_at: "2023-04-28T15:59:53+0000",
      published_at: "2023-04-28T15:59:52+0000",
      distance: null,
      contact: {
        email: "venangocountyhumanesociety@gmail.com",
        phone: "(814) 677-4040",
        address: {
          address1: "286 S. Main St",
          address2: null,
          city: "Seneca",
          state: "PA",
          postcode: "16346",
          country: "US",
        },
      },
      _links: {
        self: {
          href: "/v2/animals/63594665",
        },
        type: {
          href: "/v2/types/dog",
        },
        organization: {
          href: "/v2/organizations/pa275",
        },
      },
    },
  ],
  pagination: {
    count_per_page: 20,
    total_count: 257731,
    current_page: 1,
    total_pages: 12887,
    _links: {
      next: {
        href: "/v2/animals?page=2",
      },
    },
  },
};
